version: "3.4"
services:
  server:
    build:
      context: ../my-server/
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - PORT=3300
    volumes:
      - ./:/home/mounted-volume
    ports:
      - 5500:3300
